---
- name: Add /usr/local/bin/zsh to /etc/shells
  lineinfile: >
    dest=/etc/shells
    group=wheel
    line=/usr/local/bin/zsh
    owner=root
  become: !!bool yes

- name: Change default shell to zsh
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/local/bin/zsh
  become: !!bool yes
