---
- name: Make ~/.config/nvm
  file: path=~/.config/nvm state=directory

# Assumes that nvm was installed with Homebrew, sources nvm.sh at the location Homebrew installs it
- name: Install the latest LTS node
  shell: "NVM_DIR=$HOME/.config/nvm && source /usr/local/opt/nvm/nvm.sh && nvm install --lts && nvm alias default lts/*"
  args:
    creates: "{{ ansible_env.HOME }}/.config/nvm/versions/node"
