---
- hosts: localhost
  roles:
    - { role: ssh, tags: ssh }
    - { role: terminfo, tags: terminfo }
    - { role: homebrew, tags: homebrew }
    - { role: dotfiles, tags: dotfiles }
    - { role: shell, tags: shell }
    - { role: nodejs, tags: nodejs }
    - { role: ruby, tags: ruby }
    - { role: python, tags: python }
    - { role: vim, tags: vim }
    - { role: vagrant, tags: vagrant }
    - { role: macos, tags: macos }
