---
- name: Ensure vagrant is installed
  stat:
    path: /usr/local/bin/vagrant
  register: vagrant_check
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Get installed plugins
  shell: >
    set -o pipefail &&
    /usr/local/bin/vagrant plugin list | cut -d ' ' -f 1 | grep -v ^$
  register: vagrant_installed_plugins
  when: vagrant_check.stat.exists
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Install plugins
  command: /usr/local/bin/vagrant plugin install {{ item }}
  loop: "{{ vagrant_plugins }}"
  when:
    - vagrant_check.stat.exists
    - item not in vagrant_installed_plugins.stdout_lines
