---
- name: Set computername
  command: scutil --set ComputerName {{ computer_hostname }}
  become: true
  when: ansible_hostname != computer_hostname

- name: Set hostname
  command: scutil --set HostName {{ computer_hostname }}
  become: true
  when: ansible_hostname != computer_hostname

- name: Set localhostname
  command: scutil --set LocalHostName {{ computer_hostname }}
  become: true
  when: ansible_hostname != computer_hostname

- name: Set the netbios name
  become: true
  osx_defaults:
    domain: com.apple.smb.server
    key: NetBIOSName
    type: string
    value: "{{ computer_hostname }}"
    state: present

- name: Disable Siri
  osx_defaults:
    domain: com.apple.assistant.support
    key: Assistant Enabled
    type: bool
    value: false

- name: Show all file extensions
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
