---
- name: Download vim-plug
  get_url:
    url="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest={{ vim_plug }}
  register: vim_plug_bootstrap_install

- name: Install vim-plug plugins
  command:
    "vim +'PlugInstall --sync' +qall &>/dev/null"
  when: vim_plug_bootstrap_install is changed
