---
- name: Ensure rbenv is installed
  stat:
    path: /usr/local/bin/rbenv
  register: rbenv_check
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Create ~/.rbenv
  file:
    path: ~/.rbenv
    state: directory

- name: Setup default gems
  copy:
    src: default-gems
    dest: ~/.rbenv/default-gems
  when: rbenv_check.stat.exists

- name: Install ruby {{ ruby_version }} with rbenv
  command: /usr/local/bin/rbenv install --skip-existing {{ ruby_version }}
  args:
    creates: ~/.rbenv/versions/{{ ruby_version }}
  when: rbenv_check.stat.exists

- name: Check if global ruby version is {{ ruby_version }}
  shell: >
    set -o pipefail &&
    /usr/local/bin/rbenv version | cut -d ' ' -f 1 | grep -Fx {{ ruby_version }}
  register: ruby_selected
  changed_when: false
  failed_when: false
  when: rbenv_check.stat.exists

- name: Set ruby {{ ruby_version }} as global version
  shell: >
    /usr/local/bin/rbenv global {{ ruby_version }} &&
    /usr/local/bin/rbenv rehash
  when:
    - rbenv_check.stat.exists
    - ruby_selected.rc != 0
